name: Weapon_API
version: '${project.version}'
main: net.maidkleid.weaponapi.WeaponAPI
api-version: 1.19
authors: [ Hero_JonasHD ]
commands:
  weapon:
    aliases:
      - w
      - weapons
      - wapi
    description: lol
  
